# NOTE The below is the Docker Compose specification version NOT the Python version:
version: "3.8"

services:
  rcpchgrowth-python:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    tty: true # Allocate a pseudo-TTY
    stdin_open: true # Keep stdin open
    command: |
      pytest
