version: "3.12"

services:
  rcpchgrowth-python:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    tty: true # Allocate a pseudo-TTY
    stdin_open: true # Keep stdin open
    container_name: rcpchgrowth-python